spring.application.name=authenticationservice
spring.datasource.url=jdbc:mysql://localhost:3306/authentication?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET:a05052af5faaea9dbff3336acf9eb943b4892d158424ceda279e5a475d6b1625}
#app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B59}
app.jwt.access-token-expiration-ms=${JWT_ACCESS_EXP_MS:900000}
app.jwt.refresh-token-expiration-ms=${JWT_REFRESH_EXP_MS:604800000}